name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      - name: build
        run: gradle BuildJar

      - name: test
        run: gradle RunTest

      - name: copy resource
        run: gradle copyResources

      - name: create zip
        run: gradle createZip

      - name: run
        run: java -jar build/libs/my-application-1.0-SNAPSHOT.jar
